##############################################################
##         Initial Encounter Configuration                  ##
## Script Generated for Undergrad class of microelectronics ##
## Generated by Matheus Moreira/Fernando Moraes - 2018      ##
##                                                          ##
## Functionalities of this script:                          ##
##  -Add filler cells to the design                         ##
##  -Generate a summary report of the final design          ##
##############################################################
##Add filler cells
add_fillers -base_cells FEED1 FEED2 FEED3 FEED5 FEED7 FEED10 FEED15 FEED25 -prefix FILLER

##Generate reports
report_summary -out_dir summaryReport
time_design -post_route

eval_legacy { verifyGeometry -noOverlap }
